ConsoleWrite('MANEJO NAVIERO(1034)|'&StringRegExpReplace('MANEJO NAVIERO(1034)', '\D', '') & @CRLF)
ConsoleWrite('USO INSTALACIONES(1003)|'&StringRegExpReplace('USO INSTALACIONES(1003)', '\D', '') & @CRLF)
ConsoleWrite('BODEGAJE (1004)|'&StringRegExpReplace('BODEGAJE (1004)', '\D', '') & @CRLF)
ConsoleWrite('VUCE (1016)|'&StringRegExpReplace('VUCE (1016)', '\D', '') & @CRLF)
ConsoleWrite('VACIADO (1008)|'&StringRegExpReplace('VACIADO (1008)', '\D', '') & @CRLF)
ConsoleWrite('INSPECCION DIAN (1042)|'&StringRegExpReplace('INSPECCION DIAN (1042)', '\D', '') & @CRLF)
ConsoleWrite('DEPOSITO CONTENEDOR(1010)|'&StringRegExpReplace('DEPOSITO CONTENEDOR(1010)', '\D', '') & @CRLF)
ConsoleWrite('LIBERACION Y MANEJO GUIA(1005)|'&StringRegExpReplace('LIBERACION Y MANEJO GUIA(1005)', '\D', '') & @CRLF)
ConsoleWrite('DEMORAS CONTENEDOR(1011)|'&StringRegExpReplace('DEMORAS CONTENEDOR(1011)', '\D', '') & @CRLF)
ConsoleWrite('MOVILIZACION INSPECCION (1043)|'&StringRegExpReplace('MOVILIZACION INSPECCION (1043)', '\D', '') & @CRLF)
ConsoleWrite('ARANCEL(1001)|'&StringRegExpReplace('ARANCEL(1001)', '\D', '') & @CRLF)
ConsoleWrite('IVA (1002)|'&StringRegExpReplace('IVA (1002)', '\D', '') & @CRLF)
ConsoleWrite('MAQUINA INTERNA (1061)|'&StringRegExpReplace('MAQUINA INTERNA (1061)', '\D', '') & @CRLF)
ConsoleWrite('VISTOS BUENOS (1023)|'&StringRegExpReplace('VISTOS BUENOS (1023)', '\D', '') & @CRLF)
ConsoleWrite('CARGUE Y DESCARGUE(1025)|'&StringRegExpReplace('CARGUE Y DESCARGUE(1025)', '\D', '') & @CRLF)
ConsoleWrite('PORTEO (1024)|'&StringRegExpReplace('PORTEO (1024)', '\D', '') & @CRLF)
ConsoleWrite('INSPECCION RECONOCIMIENTO(1046)|'&StringRegExpReplace('INSPECCION RECONOCIMIENTO(1046)', '\D', '') & @CRLF)
ConsoleWrite('TRASLADO(1018)|'&StringRegExpReplace('TRASLADO(1018)', '\D', '') & @CRLF)
ConsoleWrite('STACKER(1045)|'&StringRegExpReplace('STACKER(1045)', '\D', '') & @CRLF)
ConsoleWrite('DAÑOS (1050)|'&StringRegExpReplace('DAÑOS (1050)', '\D', '') & @CRLF)
ConsoleWrite('SUCIEDAD (1026)|'&StringRegExpReplace('SUCIEDAD (1026)', '\D', '') & @CRLF)
ConsoleWrite('EMISION BL (1028)|'&StringRegExpReplace('EMISION BL (1028)', '\D', '') & @CRLF)
ConsoleWrite('APERTURA Y CIERRE (1015)|'&StringRegExpReplace('APERTURA Y CIERRE (1015)', '\D', '') & @CRLF)
ConsoleWrite('CERTIFICADOS (1020)|'&StringRegExpReplace('CERTIFICADOS (1020)', '\D', '') & @CRLF)
ConsoleWrite('BASCULAS(1029)|'&StringRegExpReplace('BASCULAS(1029)', '\D', '') & @CRLF)
ConsoleWrite('PAPELERIA (1038)|'&StringRegExpReplace('PAPELERIA (1038)', '\D', '') & @CRLF)
ConsoleWrite('CAMBIO MODALIDAD (1048)|'&StringRegExpReplace('CAMBIO MODALIDAD (1048)', '\D', '') & @CRLF)
ConsoleWrite('HORA ADICIONAL (1052)|'&StringRegExpReplace('HORA ADICIONAL (1052)', '\D', '') & @CRLF)
ConsoleWrite('CARGO FIJO (1054)|'&StringRegExpReplace('CARGO FIJO (1054)', '\D', '') & @CRLF)
ConsoleWrite('MANEJO DE DOCUMENTOS(1006)|'&StringRegExpReplace('MANEJO DE DOCUMENTOS(1006)', '\D', '') & @CRLF)
ConsoleWrite('CAMA ALTA-BAJA (1044)|'&StringRegExpReplace('CAMA ALTA-BAJA (1044)', '\D', '') & @CRLF)
ConsoleWrite('SERVICIO DE CARPADO(1060)|'&StringRegExpReplace('SERVICIO DE CARPADO(1060)', '\D', '') & @CRLF)
ConsoleWrite('SERVICIOCONSOLIDACION(1007)|'&StringRegExpReplace('SERVICIOCONSOLIDACION(1007)', '\D', '') & @CRLF)
ConsoleWrite('COMODATOS (1039)|'&StringRegExpReplace('COMODATOS (1039)', '\D', '') & @CRLF)
ConsoleWrite('TRABAJOS VARIOS HORAS/HOMBRES (1049)|'&StringRegExpReplace('TRABAJOS VARIOS HORAS/HOMBRES (1049)', '\D', '') & @CRLF)
ConsoleWrite('SELLOS DE CONTENEDOR (1051)|'&StringRegExpReplace('SELLOS DE CONTENEDOR (1051)', '\D', '') & @CRLF)
ConsoleWrite('ENVIO (1031)|'&StringRegExpReplace('ENVIO (1031)', '\D', '') & @CRLF)
ConsoleWrite('DISMOUNTING (1012)|'&StringRegExpReplace('DISMOUNTING (1012)', '\D', '') & @CRLF)
ConsoleWrite('TRANSPORTE (1027)|'&StringRegExpReplace('TRANSPORTE (1027)', '\D', '') & @CRLF)
ConsoleWrite('ADICIONAL 1 (1022)|'&StringRegExpReplace('ADICIONAL 1 (1022)', '\D', '') & @CRLF)
ConsoleWrite('ADICIONAL 2 (1032)|'&StringRegExpReplace('ADICIONAL 2 (1032)', '\D', '') & @CRLF)
ConsoleWrite('ADICIONAL 3(1041)|'&StringRegExpReplace('ADICIONAL 3(1041)', '\D', '') & @CRLF)
ConsoleWrite('ADICIONAL 4 (1009)|'&StringRegExpReplace('ADICIONAL 4 (1009)', '\D', '') & @CRLF)
ConsoleWrite('SERVICIO EXTRAORDINARIO (1014)|'&StringRegExpReplace('SERVICIO EXTRAORDINARIO (1014)', '\D', '') & @CRLF)
ConsoleWrite('VR 4XMIL(1030)|'&StringRegExpReplace('VR 4XMIL(1030)', '\D', '') & @CRLF)
ConsoleWrite('SUBTOTAL|'&StringRegExpReplace('SUBTOTAL', '\D', '') & @CRLF)
ConsoleWrite('SERVICIO ADUANA(2003)|'&StringRegExpReplace('SERVICIO ADUANA(2003)', '\D', '') & @CRLF)
ConsoleWrite('RECONOCIMIENTO MCIA(2052)|'&StringRegExpReplace('RECONOCIMIENTO MCIA(2052)', '\D', '') & @CRLF)
ConsoleWrite('ELABORACION REGISTROS DE IMP. (2005)|'&StringRegExpReplace('ELABORACION REGISTROS DE IMP. (2005)', '\D', '') & @CRLF)
ConsoleWrite('ELABORACIONDECLARACIONES DE IMPORTACION (2009)|'&StringRegExpReplace('ELABORACIONDECLARACIONES DE IMPORTACION (2009)', '\D', '') & @CRLF)
ConsoleWrite('ELABORACION DECLARACIONES DE VALOR(2042)|'&StringRegExpReplace('ELABORACION DECLARACIONES DE VALOR(2042)', '\D', '') & @CRLF)
ConsoleWrite('DESCARGUE DIRECTO(2007)|'&StringRegExpReplace('DESCARGUE DIRECTO(2007)', '\D', '') & @CRLF)
ConsoleWrite('VISTO BUENO (2045)|'&StringRegExpReplace('VISTO BUENO (2045)', '\D', '') & @CRLF)
