ConsoleWrite(StringRegExpReplace('MANEJO NAVIERO(1034)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('USO INSTALACIONES(1003)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('BODEGAJE (1004)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('VUCE (1016)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('VACIADO (1008)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('INSPECCION DIAN (1042)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('DEPOSITO CONTENEDOR(1010)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('LIBERACION Y MANEJO GUIA(1005)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('DEMORAS CONTENEDOR(1011)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('MOVILIZACION INSPECCION (1043)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ARANCEL(1001)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('IVA (1002)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('MAQUINA INTERNA (1061)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('VISTOS BUENOS (1023)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('CARGUE Y DESCARGUE(1025)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('PORTEO (1024)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('INSPECCION RECONOCIMIENTO(1046)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('TRASLADO(1018)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('STACKER(1045)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('DAÑOS (1050)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SUCIEDAD (1026)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('EMISION BL (1028)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('APERTURA Y CIERRE (1015)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('CERTIFICADOS (1020)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('BASCULAS(1029)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('PAPELERIA (1038)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('CAMBIO MODALIDAD (1048)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('HORA ADICIONAL (1052)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('CARGO FIJO (1054)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('MANEJO DE DOCUMENTOS(1006)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('CAMA ALTA-BAJA (1044)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SERVICIO DE CARPADO(1060)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SERVICIOCONSOLIDACION(1007)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('COMODATOS (1039)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('TRABAJOS VARIOS HORAS/HOMBRES (1049)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SELLOS DE CONTENEDOR (1051)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ENVIO (1031)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('DISMOUNTING (1012)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('TRANSPORTE (1027)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ADICIONAL 1 (1022)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ADICIONAL 2 (1032)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ADICIONAL 3(1041)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ADICIONAL 4 (1009)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SERVICIO EXTRAORDINARIO (1014)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('VR 4XMIL(1030)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SUBTOTAL', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('SERVICIO ADUANA(2003)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('RECONOCIMIENTO MCIA(2052)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ELABORACION REGISTROS DE IMP. (2005)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ELABORACIONDECLARACIONES DE IMPORTACION (2009)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('ELABORACION DECLARACIONES DE VALOR(2042)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('DESCARGUE DIRECTO(2007)', '\D', '')& @CRLF)
ConsoleWrite(StringRegExpReplace('VISTO BUENO (2045)', '\D', '')& @CRLF)
