ConsoleWrite(Number('MANEJO NAVIERO                            (1034)')&@CRLF)
ConsoleWrite(Number('USO INSTALACIONES(1003)')&@CRLF)
ConsoleWrite(Number('BODEGAJE (1004)')&@CRLF)
ConsoleWrite(Number('VUCE               (1016)')&@CRLF)
ConsoleWrite(Number('VACIADO       (1008)')&@CRLF)
ConsoleWrite(Number('INSPECCION DIAN (1042)')&@CRLF)
ConsoleWrite(Number('DEPOSITO CONTENEDOR  (1010)')&@CRLF)
ConsoleWrite(Number('LIBERACION Y MANEJO GUIA  (1005)')&@CRLF)
ConsoleWrite(Number('DEMORAS CONTENEDOR  (1011)')&@CRLF)
ConsoleWrite(Number('MOVILIZACION INSPECCION (1043)')&@CRLF)
ConsoleWrite(Number('ARANCEL      (1001)')&@CRLF)
ConsoleWrite(Number('IVA                   (1002)')&@CRLF)
ConsoleWrite(Number('MAQUINA INTERNA         (1061)')&@CRLF)
ConsoleWrite(Number('VISTOS BUENOS   (1023)')&@CRLF)
ConsoleWrite(Number('CARGUE Y DESCARGUE  (1025)')&@CRLF)
ConsoleWrite(Number('PORTEO         (1024)')&@CRLF)
ConsoleWrite(Number('INSPECCION RECONOCIMIENTO(1046)')&@CRLF)
ConsoleWrite(Number('TRASLADO    (1018)')&@CRLF)
ConsoleWrite(Number('STACKER      (1045)')&@CRLF)
ConsoleWrite(Number('DAÑOS           (1050)')&@CRLF)
ConsoleWrite(Number('SUCIEDAD     (1026)')&@CRLF)
ConsoleWrite(Number('EMISION BL     (1028)')&@CRLF)
ConsoleWrite(Number('APERTURA Y CIERRE (1015)')&@CRLF)
ConsoleWrite(Number('CERTIFICADOS (1020)')&@CRLF)
ConsoleWrite(Number('BASCULAS    (1029)')&@CRLF)
ConsoleWrite(Number('PAPELERIA       (1038)')&@CRLF)
ConsoleWrite(Number('CAMBIO MODALIDAD     (1048)')&@CRLF)
ConsoleWrite(Number('HORA ADICIONAL     (1052)')&@CRLF)
ConsoleWrite(Number('CARGO FIJO   (1054)')&@CRLF)
ConsoleWrite(Number('MANEJO DE DOCUMENTOS(1006)')&@CRLF)
ConsoleWrite(Number('CAMA ALTA-BAJA (1044)')&@CRLF)
ConsoleWrite(Number('SERVICIO DE CARPADO      (1060)')&@CRLF)
ConsoleWrite(Number('SERVICIO  CONSOLIDACION  (1007)')&@CRLF)
ConsoleWrite(Number('COMODATOS (1039)')&@CRLF)
ConsoleWrite(Number('TRABAJOS VARIOS HORAS/HOMBRES (1049)')&@CRLF)
ConsoleWrite(Number('SELLOS DE CONTENEDOR   (1051)')&@CRLF)
ConsoleWrite(Number('ENVIO             (1031)')&@CRLF)
ConsoleWrite(Number('DISMOUNTING (1012)')&@CRLF)
ConsoleWrite(Number('TRANSPORTE (1027)')&@CRLF)
ConsoleWrite(Number('ADICIONAL 1 (1022)')&@CRLF)
ConsoleWrite(Number('ADICIONAL 2   (1032)')&@CRLF)
ConsoleWrite(Number('ADICIONAL 3    (1041)')&@CRLF)
ConsoleWrite(Number('ADICIONAL 4 (1009)')&@CRLF)
ConsoleWrite(Number('SERVICIO EXTRAORDINARIO (1014)')&@CRLF)
ConsoleWrite(Number('VR 4XMIL        (1030)')&@CRLF)
ConsoleWrite(Number('SUBTOTAL')&@CRLF)
ConsoleWrite(Number('SERVICIO ADUANA        (2003)')&@CRLF)
ConsoleWrite(Number('RECONOCIMIENTO MCIA            (2052)')&@CRLF)
ConsoleWrite(Number('ELABORACION REGISTROS DE IMP. (2005)')&@CRLF)
ConsoleWrite(Number('ELABORACION  DECLARACIONES DE IMPORTACION (2009)')&@CRLF)
ConsoleWrite(Number('ELABORACION DECLARACIONES DE VALOR  (2042)')&@CRLF)
ConsoleWrite(Number('DESCARGUE DIRECTO  (2007)')&@CRLF)
ConsoleWrite(Number('VISTO BUENO (2045)')&@CRLF)